Welcome to the best book for learning to use the Vim text editor in the most powerful, sustainable way. This includes `vi` (pronouced vee-eye), `vim`, and `nvim` (Neovim).

You have probably discovered  a _lot_ of stuff about Vim on the Internet and in the few books that exist. Far too much of it is legitimately bad, old, or sometimes just plain wrong—especially the infamous `vimtutor` made by a few college kids who had just _barely_ learned it. Why use `d$` when `D` is much easier, for example? `¯\_(ツ)_/¯` Other resources would have you play a game instead of actually using `vim` to learn it.

[IMPORTANT]
====
Speaking of putting bad things into your muscle memory, **DO NOT USE `Control-c` INSTEAD OF ESCAPE!** This completely prevents you from using `set -o vi` for history navigation later—one of the single biggest reasons to learn Vim in the first place—because it sends a signal interrupt that is not handled by the shell as an `Esc`! `Control-[` _does_ send an actual `Esc`.

Some very prominent tech "influencers" use `Control-c` instead. But _why_?! This makes absolutely no sense. How can anyone claim to be a Vim advocate and yet willingly teach people something that will permanently handicap them, preventing them from _ever_ using Vim for history navigation?

These same "influencers" continually trash talk Emacs, and yet they _force_ people they influence to use Emacs for any history navigation.

Either these influencers aren't _really_ committed to Vim, or just don't know what `set -o vi` even does. Either way, you should _never_ trust someone claiming to be a "Vim expert" asking you to remap `Esc` to `Control-[`. Now you know why and can tell anyone suggesting this how stupid it is. Vim mappings are everywhere. Don't start by learning this wrong. I promise, you'll be glad you didn't.
====

This book was created in response to that problem. This state of confusion frustrates and angers me. Don't get mad, get busy. So here I am putting that energy into a book that hopefully counters the problem and saves _you_ from permanently damaging your muscle memory by learning this stuff the wrong way. Save yourself the hardship and pain by learning the world's most powerful editor—the right way.

include::../../../first-person.adoc[]

