== Dear parents and pedagogues

Are you a parent or a teacher? If so, thank you for being _awesome_! It takes a lot to bring kids into this world and even more to dedicate your life to helping kids that aren't even your own to find their way and learn something even if they don't want to. Deep respect. But let's get real. You're reading this right now wondering if I'm going to corrupt your children.

The answer is yes. Yes I am. In fact, my goal is to fully corrupt them much the same as Socrates. If I am successful your children will become _better_ that the status quo, they'll think critically, ask uncomfortable questions, and use their new powers and tools to ethically disrupt this broken world transforming it into something better. They'll become the most annoying people you've ever known—in the best way possible.

Why me? Because getting people to discover this potential and realize it through their own learning is my super power. I've been mentored by the best and I'm _really_ good at it. Since the first time my scouts begged "Mr. Rob, teach us to code. Mr. Rob, teach us to hack. Mr. Rob, teach us Russian." I have been bound and determined to make this a reality. In fact, I started SKILSTAK Coding Arts in 2013 with my own retirement money to address the _real_ needs of the tech industry and those who might consider it as a career, raising a generation of highly skilled knowledge warriors.

Let me tell you about some of these amazing people:

- One of them quit his grocery clerk job to write code for a solar energy company and was paired with essentially his own intern at 16.

- Another couldn't get a job with a psychology degree so he learned this stuff and got a starting salary over $100,000.

- A few people got coveted invitations to special FBI cybersecurity camps.

- One drove 40 minutes both ways just to attend our sessions for _four years_ and went on to create an entire coding club at her rural school.

- Some got cybersecurity degrees from accredited colleges and invites to work with professional hacking crews.

It's been a blast being with these people. My favorite memories are all the times we hacked companies with permission and helped them patch their security, or shut down hackers for panicked parents whose businesses had been compromised.

The point is, these success stories don't have to be about someone else. They can be about someone _you know and love_. Terminal tech skills really do change lives and I'm here to help in whatever way I can.

